server:
  port: ${APP_PORT:8081}

spring:
  application:
    name: jmeter-builder
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
