apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-jmeter-builder
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: jmeter-builder
spec:
  replicas: {{ .Values.jmeterBuilder.replicaCount }}
  selector:
    matchLabels:
      {{- include "loadtest-portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jmeter-builder
  template:
    metadata:
      labels:
        {{- include "loadtest-portal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jmeter-builder
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "loadtest-portal.serviceAccountName" . }}
      containers:
        - name: jmeter-builder
          image: {{ include "loadtest-portal.image" (dict "Values" .Values "repo" .Values.jmeterBuilder.image.repository "tag" .Values.jmeterBuilder.image.tag) }}
          imagePullPolicy: {{ .Values.jmeterBuilder.image.pullPolicy }}
          env:
            - name: APP_PORT
              value: "8081"
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.jmeterBuilder.javaOpts | quote }}
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            {{- toYaml .Values.jmeterBuilder.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
