apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-k6-generator
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: k6-generator
spec:
  replicas: {{ .Values.k6Generator.replicaCount }}
  selector:
    matchLabels:
      {{- include "loadtest-portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: k6-generator
  template:
    metadata:
      labels:
        {{- include "loadtest-portal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: k6-generator
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "loadtest-portal.serviceAccountName" . }}
      containers:
        - name: k6-generator
          image: {{ include "loadtest-portal.image" (dict "Values" .Values "repo" .Values.k6Generator.image.repository "tag" .Values.k6Generator.image.tag) }}
          imagePullPolicy: {{ .Values.k6Generator.image.pullPolicy }}
          env:
            - name: APP_PORT
              value: "8001"
          ports:
            - name: http
              containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.k6Generator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
