{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loadtest-portal.fullname" . }}
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "loadtest-portal.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 3000
        - port: 8080
    - from:
        - podSelector:
            matchLabels:
              {{- include "loadtest-portal.selectorLabels" . | nindent 14 }}
      ports:
        - port: 8000
        - port: 8001
        - port: 8080
        - port: 8081
        - port: 5432
  egress:
    - {}
{{- end }}
