{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-frontend
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "loadtest-portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
---
{{- if .Values.constructor.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-constructor
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.constructor.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "loadtest-portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: constructor
{{- end }}
