{{- if and .Values.postgresql.internal.enabled (not .Values.externalDatabase.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-db
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.externalDatabase.username | default "loadtest" | quote }}
  password: {{ .Values.externalDatabase.password | default "loadtest-change-me" | quote }}
  database: {{ .Values.externalDatabase.database | default "loadtest" | quote }}
{{- end }}
