apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-frontend
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "loadtest-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-constructor
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: constructor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "loadtest-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: constructor
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-analyzer
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    {{- include "loadtest-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-k6-generator
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: k6-generator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
  selector:
    {{- include "loadtest-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: k6-generator
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-portal.fullname" . }}-jmeter-builder
  labels:
    {{- include "loadtest-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: jmeter-builder
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    {{- include "loadtest-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jmeter-builder
